### ISSUE TITLE
Firefox compatibility status

### ISSUE THREAD

**Issue by sbellone** [algolia/renderscript#438]
Here is the current status of Firefox's missing features to release a Firefox based renderscript with the same features:
- [ ] `networkidle0` is not supported, so we can't wait accurately for the page to finish rendering https://github.com/puppeteer/puppeteer/issues/5841#issuecomment-669934206
- [ ] [`page.metrics()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagemetrics) throws an error: https://github.com/puppeteer/puppeteer/issues/4044
- [ ] [`page.setRequestInterception()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetrequestinterceptionvalue) throws an error: https://github.com/puppeteer/puppeteer/issues/6359

Minor:
- [ ] Firefox revision is set to [`latest`](https://github.com/puppeteer/puppeteer/blob/main/src/revisions.ts#L24), but latest is not exposed anymore at https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
- [ ] `page.goto()` doesn't work with non-html protocols: https://github.com/puppeteer/puppeteer/issues/5504

<details>
<summary>Patch for a working Firefox-based renderscript (with the features above commented)</summary>
Note: Firefox instance is not closed when killing the process, to investigate

```diff
diff --git a/src/lib/browser/Browser.ts b/src/lib/browser/Browser.ts
index 9a8b470..f1dc778 100644
--- a/src/lib/browser/Browser.ts
+++ b/src/lib/browser/Browser.ts
@@ -3,7 +3,7 @@ import type { Browser as BrowserInterface } from 'puppeteer-core/lib/esm/puppete
 import { v4 as uuid } from 'uuid';

 import { stats } from 'helpers/stats';
-import { getChromiumExecutablePath } from 'lib/helpers/getChromiumExecutablePath';
+import { getBrowserExecutablePath } from 'lib/helpers/getChromiumExecutablePath';

 import { flags, HEIGHT, WIDTH } from '../constants';

@@ -40,17 +40,19 @@ export class Browser {
     }

     let start = Date.now();
+    const product = 'firefox';
     const browser = await puppeteer.launch({
       headless: true,
       env,
-      executablePath: await getChromiumExecutablePath(),
+      product,
+      executablePath: await getBrowserExecutablePath(product),
       defaultViewport: {
         width: WIDTH,
         height: HEIGHT,
       },
       handleSIGINT: false,
       handleSIGTERM: false,
-      pipe: true,
+      // pipe: true, // puppeteer.launch() never returns when pipe is true with Firefox
       args: flags,
     });
     stats.timing('renderscript.create', Date.now() - start);
@@ -58,7 +60,8 @@ export class Browser {
     // Try to load a test page first
     start = Date.now();
     const testPage = await browser.newPage();
-    await testPage.goto('about://settings', { waitUntil: 'networkidle0' });
+    // Navigating in an "about" page doesn't work with Firefox https://github.com/puppeteer/puppeteer/issues/5504
+    // await testPage.goto('about://settings', { waitUntil: 'networkidle0' });
     stats.timing('renderscript.page.initial', Date.now() - start);
     testPage.close();

diff --git a/src/lib/browser/Page.ts b/src/lib/browser/Page.ts
index 3a0acb6..12d2e7a 100644
--- a/src/lib/browser/Page.ts
+++ b/src/lib/browser/Page.ts
@@ -87,14 +87,15 @@ export class BrowserPage {
   }

   async metrics(): Promise<PageMetrics> {
-    const metrics = await this.#page!.metrics();
+    // Throws with Firefox: https://github.com/puppeteer/puppeteer/issues/4044
+    // const metrics = await this.#page!.metrics();
     return {
       ...this.#metrics,
-      layoutDuration: Math.round((metrics.LayoutDuration || 0) * 1000),
-      scriptDuration: Math.round((metrics.ScriptDuration || 0) * 1000),
-      taskDuration: Math.round((metrics.TaskDuration || 0) * 1000),
-      jsHeapUsedSize: metrics.JSHeapUsedSize || 0,
-      jsHeapTotalSize: metrics.JSHeapTotalSize || 0,
+      // layoutDuration: Math.round((metrics.LayoutDuration || 0) * 1000),
+      // scriptDuration: Math.round((metrics.ScriptDuration || 0) * 1000),
+      // taskDuration: Math.round((metrics.TaskDuration || 0) * 1000),
+      // jsHeapUsedSize: metrics.JSHeapUsedSize || 0,
+      // jsHeapTotalSize: metrics.JSHeapTotalSize || 0,
     };
   }

@@ -117,7 +118,8 @@ export class BrowserPage {
     try {
       response = await this.#page!.goto(url.href, {
         timeout,
-        waitUntil: ['domcontentloaded', 'networkidle0'],
+        // https://github.com/puppeteer/puppeteer/issues/5841#issuecomment-669934206
+        waitUntil: ['domcontentloaded' /* , 'networkidle0'*/],
       });
     } catch (e: any) {
       if (e.message.match(/Navigation Timeout Exceeded/)) {
@@ -153,7 +155,8 @@ export class BrowserPage {

     await this.#page!.setUserAgent(userAgent);

-    await this.#page!.setRequestInterception(true);
+    // https://github.com/puppeteer/puppeteer/issues/6359
+    // await this.#page!.setRequestInterception(true);
     if (headersToForward.cookie) {
       const cookies = headersToForward.cookie.split('; ').map((cookie) => {
         const [key, ...v] = cookie.split('=');
diff --git a/src/lib/helpers/getChromiumExecutablePath.ts b/src/lib/helpers/getChromiumExecutablePath.ts
index c23507a..1aae60e 100644
--- a/src/lib/helpers/getChromiumExecutablePath.ts
+++ b/src/lib/helpers/getChromiumExecutablePath.ts
@@ -1,23 +1,24 @@
 import puppeteer from 'puppeteer-core';

-export async function getChromiumExecutablePath(): Promise<string> {
+export async function getBrowserExecutablePath(
+  product: string = 'chrome'
+): Promise<string> {
   // eslint-disable-next-line @typescript-eslint/no-var-requires
   const revisions = require('puppeteer-core/lib/cjs/puppeteer/revisions.js');
-  const {
-    PUPPETEER_REVISIONS: { chromium: revision },
-  } = revisions;
+  const revision =
+    product === 'firefox' ? '95.0a1' : revisions.PUPPETEER_REVISIONS.chromium;

-  const fetcher = puppeteer.createBrowserFetcher({});
+  const fetcher = puppeteer.createBrowserFetcher({ product });
   const localRevisions = await fetcher.localRevisions();

   let revisionInfo;
   if (localRevisions.includes(revision)) {
     revisionInfo = fetcher.revisionInfo(revision);
-    console.info(`Local Chromium rev ${revision} already present`);
+    console.info(`Local ${product} rev ${revision} already present`);
   } else {
-    console.info(`Downloading Chromium rev ${revision}...`);
+    console.info(`Downloading ${product} rev ${revision}...`);
     revisionInfo = await fetcher.download(revision);
-    console.info(`Downloaded Chromium rev ${revision}`);
+    console.info(`Downloaded ${product} rev ${revision}`);
   }

   return revisionInfo.executablePath;
diff --git a/src/lib/install.ts b/src/lib/install.ts
index 08f378c..8f3868a 100644
--- a/src/lib/install.ts
+++ b/src/lib/install.ts
@@ -1,5 +1,5 @@
-import { getChromiumExecutablePath } from 'lib/helpers/getChromiumExecutablePath';
+import { getBrowserExecutablePath } from 'lib/helpers/getChromiumExecutablePath';

 (async (): Promise<void> => {
-  await Promise.all([getChromiumExecutablePath()]);
+  await Promise.all([getBrowserExecutablePath()]);
 })();
```
</details>

**Comment by sbellone** [comment]
Firefox support has been added in #665, thanks to the switch to Playwright.
